version: '3.3'
services:
  app:
    ports:
      - "8090:8090"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 759153
      MYSQL_DATABASE: GPTest
      MYSQL_USER: root
      MYSQL_PASSWORD: 759153